
services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eventicmind_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend FastAPI Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/eventicmind_db
      - JWT_SECRET_KEY=ePJVSkFfl2lyn7hZtfLSmUbI1Lj4kxqUiwdlUw-UwCM
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000,http://localhost:8080
      - OLLAMA_MODEL=mistral
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app

  # Frontend Vite/React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    restart: always
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: